// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generation.sql

package db

import (
	"context"
)

const getGeneration = `-- name: GetGeneration :one
SELECT id, user_id, voice_id, voice_name, text, r2_object_key, temperature, top_p, top_k, repetition_penalty, created_at, updated_at FROM generations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGeneration(ctx context.Context, id string) (Generation, error) {
	row := q.db.QueryRowContext(ctx, getGeneration, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VoiceID,
		&i.VoiceName,
		&i.Text,
		&i.R2ObjectKey,
		&i.Temperature,
		&i.TopP,
		&i.TopK,
		&i.RepetitionPenalty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
