// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Generation struct {
	ID                string         `json:"id"`
	UserID            string         `json:"user_id"`
	VoiceID           sql.NullString `json:"voice_id"`
	VoiceName         string         `json:"voice_name"`
	Text              string         `json:"text"`
	R2ObjectKey       sql.NullString `json:"r2_object_key"`
	Temperature       float64        `json:"temperature"`
	TopP              float64        `json:"top_p"`
	TopK              int32          `json:"top_k"`
	RepetitionPenalty float64        `json:"repetition_penalty"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
